### PR TITLE
Iss1064 dc excep fix

### LINKED ISSUE #1064: Need to address new DC exception
found one in file clas_006225.evio.00040-00044.hipo

```
2023-02-24 20:36:46.976: Processed  500 events in  10.96 s   average event time =  21.91 ms   [ total 307000 events  6266.55 s ]
2023-02-24 20:36:57.244: Processed  500 events in  10.27 s   average event time =  20.53 ms   [ total 307500 events  6276.81 s ]
2023-02-24 20:36:59.281: Error in 129.57.70.16%7920_java:devita:DCHAI (ID: 307644):
Error processing input event

java.lang.NullPointerException
        at org.jlab.rec.dc.track.Track.isGood(Track.java:415)
        at org.jlab.rec.dc.track.TrackCandListFinder.removeOverlappingTracks(TrackCandListFinder.java:667)
        at org.jlab.service.dc.DCHBPostClusterAI.processDataEvent(DCHBPostClusterAI.java:129)
        at org.jlab.clas.reco.ReconstructionEngine.execute(ReconstructionEngine.java:376)
        at org.jlab.clara.sys.ServiceEngine.executeEngine(ServiceEngine.java:227)
        at org.jlab.clara.sys.ServiceEngine.execute(ServiceEngine.java:153)
        at org.jlab.clara.sys.Service.lambda$execute$2(Service.java:178)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

### PR DESCRIPTION
**Pull request by zieglerv**

### CODE REVIEW

File: reconstruction/dc/src/main/java/org/jlab/rec/dc/track/Track.java [hunk 1]
```diff
@@ -411,6 +411,7 @@ public boolean bestChi2(Track o) {
     }
     
     public boolean isGood() {
+        if(this._trakOrig==null) return false;
```
Comment (raffaelladevita) [inline reconstruction/dc/src/main/java/org/jlab/rec/dc/track/Track.java:414]: the new check should be integrated in the if at line 416 or we should break the latter into 
if(...)
   return false;
getting rid of the Boolean variable

**Review by raffaelladevita — CHANGES_REQUESTED** [review]

**Review by raffaelladevita — APPROVED** [review]
