### PR TITLE
Iss897 all dc fixes n improv

### LINKED ISSUE #824: Doca Beta-dependent correction
Implement new beta-dependent correction to the doca.  Subtract correction from doca computed from the T2D tables interpolation. (The T2D tables are filled for beta=0.)

### LINKED ISSUE #881: use tdc jitter correction in DC

### LINKED ISSUE #888: DC T2D function interpolation in time bin fix
fix the interpolation as a function of time

### LINKED ISSUE #894: DC: fix isochrones b-field correction formula
switch from torus scale to polarity

### LINKED ISSUE #897: Branch with all DC fixes and improvements
Create a branch with all DC fixes and improvements

### PR DESCRIPTION
**Pull request by zieglerv**

### CODE REVIEW

File: reconstruction/dc/src/main/java/org/jlab/service/dc/DCEngine.java [hunk 1]
```diff
@@ -60,7 +60,7 @@ else if(this.getEngineConfigString("variation")!=null)
         //Use time in tBeta function (true: use time; false: use track doca)
         if(this.getEngineConfigString("dcTimeTBeta")!=null)
             useTimeBeta = (Boolean.valueOf(this.getEngineConfigString("dcTimeTBeta")));
-        
+            useTimeBeta =false; //always force to false
```
Comment (raffaelladevita) [inline reconstruction/dc/src/main/java/org/jlab/service/dc/DCEngine.java:63]: if useTimeBeta is disabled, can we remove the yaml variable?

**Review by raffaelladevita — APPROVED** [review]

File: reconstruction/dc/src/main/java/org/jlab/service/dc/DCEngine.java (hunk 1 above)
Comment (hauenst) [reply reconstruction/dc/src/main/java/org/jlab/service/dc/DCEngine.java:63]: Veronique should comment on this. I wouldn't mind to remove the yaml variable

**Review by hauenst — APPROVED** [review]
Check of time jitter correction. As presented in CLAS12software meeting, the sign in the code has to be "-" to have a correction like the RICH but we will use inverted values in CCDB to compensate for the time stamp issue
[timejitterchecks.pdf](https://github.com/JeffersonLab/clas12-offline-software/files/9114397/timejitterchecks.pdf)

Check of pressure dependent code with old (8.1.0)+time2dist table and new software with pressure dependent tables. Exact same results for reconstructed hits and electron kinematics. 
[pressure_comp_mom_oldnew.pdf](https://github.com/JeffersonLab/clas12-offline-software/files/9114399/pressure_comp_mom_oldnew.pdf)

Further checks/slides at the CLAS12software meetings at https://clasweb.jlab.org/wiki/index.php/Clas12_software_meetings_2022
